// vue-app/src/components/CrudObjetos.vue
<template>
  <div class="crud-container">
    <h2>CRUD Objetos</h2>
    <div style="text-align:center; margin-bottom:12px">
      <input v-model="nombre" placeholder="Nombre del objeto" />
      <button v-if="editId" @click="handleUpdate">Actualizar</button>
      <button v-if="editId" @click="handleCancel" style="background:#bbb; color:#222">Cancelar</button>
      <button v-else @click="handleAdd">Agregar</button>
    </div>
    <p v-if="mensaje" style="color:green; text-align:center">{{ mensaje }}</p>
    <p v-if="error" style="color:red; text-align:center">{{ error }}</p>
    <table class="crud-table">
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Acciones</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="obj in objetos" :key="obj.id">
          <td>{{ obj.nombre }}</td>
          <td>
            <button @click="handleEdit(obj)">Editar</button>
            <button @click="handleDelete(obj.id)" style="background:#c62828">Borrar</button>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script setup>
import { ref, onMounted } from "vue";
import { db } from "../firebaseConfig";
import {
  collection,
  addDoc,
  getDocs,
  updateDoc,
  deleteDoc,
  doc,
} from "firebase/firestore";

const objetos = ref([]);
const nombre = ref("");
const editId = ref(null);
const mensaje = ref("");
const error = ref("");

const fetchObjetos = async () => {
  try {
    const snapshot = await getDocs(collection(db, "objetos"));
    objetos.value = snapshot.docs.map((doc) => ({
      id: doc.id,
      ...doc.data(),
    }));
  } catch (err) {
    error.value = "Error al cargar objetos.";
  }
};

onMounted(fetchObjetos);

const handleAdd = async () => {
  mensaje.value = "";
  error.value = "";
  if (!nombre.value) {
    error.value = "El nombre no puede estar vacío.";
    return;
  }
  try {
    await addDoc(collection(db, "objetos"), { nombre: nombre.value });
    nombre.value = "";
    mensaje.value = "Objeto agregado.";
    fetchObjetos();
  } catch (err) {
    error.value = "Error al agregar: " + err.message;
  }
};

const handleEdit = (obj) => {
  editId.value = obj.id;
  nombre.value = obj.nombre;
  mensaje.value = "";
  error.value = "";
};

const handleUpdate = async () => {
  mensaje.value = "";
  error.value = "";
  if (!nombre.value) {
    error.value = "El nombre no puede estar vacío.";
    return;
  }
  try {
    await updateDoc(doc(db, "objetos", editId.value), { nombre: nombre.value });
    editId.value = null;
    nombre.value = "";
    mensaje.value = "Objeto actualizado.";
    fetchObjetos();
  } catch (err) {
    error.value = "Error al actualizar: " + err.message;
  }
};

const handleDelete = async (id) => {
  if (!confirm("¿Seguro que deseas borrar este objeto?")) return;
  mensaje.value = "";
  error.value = "";
  try {
    await deleteDoc(doc(db, "objetos", id));
    mensaje.value = "Objeto borrado.";
    fetchObjetos();
  } catch (err) {
    error.value = "Error al borrar: " + err.message;
  }
};

const handleCancel = () => {
  editId.value = null;
  nombre.value = "";
  mensaje.value = "";
  error.value = "";
};
</script>

// react-app/src/Componentes/CrudObjetos.js
import React, { useEffect, useState } from "react";
import { db } from "../firebaseConfig";
import {
  collection,
  addDoc,
  getDocs,
  updateDoc,
  deleteDoc,
  doc
} from "firebase/firestore";

export default function CrudObjetos() {
  const [objetos, setObjetos] = useState([]);
  const [nombre, setNombre] = useState("");
  const [editId, setEditId] = useState(null);
  const [mensaje, setMensaje] = useState("");
  const [error, setError] = useState("");

  const fetchObjetos = async () => {
    try {
      const snapshot = await getDocs(collection(db, "objetos"));
      setObjetos(snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() })));
    } catch (err) {
      setError("Error al cargar objetos.");
    }
  };

  useEffect(() => {
    fetchObjetos();
  }, []);

  const handleAdd = async () => {
    setMensaje("");
    setError("");
    if (!nombre) {
      setError("El nombre no puede estar vacío.");
      return;
    }
    try {
      await addDoc(collection(db, "objetos"), { nombre });
      setNombre("");
      setMensaje("Objeto agregado.");
      fetchObjetos();
    } catch (err) {
      setError("Error al agregar: " + err.message);
    }
  };

  const handleEdit = (obj) => {
    setEditId(obj.id);
    setNombre(obj.nombre);
    setMensaje("");
    setError("");
  };

  const handleUpdate = async () => {
    setMensaje("");
    setError("");
    if (!nombre) {
      setError("El nombre no puede estar vacío.");
      return;
    }
    try {
      await updateDoc(doc(db, "objetos", editId), { nombre });
      setEditId(null);
      setNombre("");
      setMensaje("Objeto actualizado.");
      fetchObjetos();
    } catch (err) {
      setError("Error al actualizar: " + err.message);
    }
  };

  const handleDelete = async (id) => {
    if (!window.confirm("¿Seguro que deseas borrar este objeto?")) return;
    setMensaje("");
    setError("");
    try {
      await deleteDoc(doc(db, "objetos", id));
      setMensaje("Objeto borrado.");
      fetchObjetos();
    } catch (err) {
      setError("Error al borrar: " + err.message);
    }
  };

  const handleCancel = () => {
    setEditId(null);
    setNombre("");
    setMensaje("");
    setError("");
  };

  return (
    <div className="crud-container">
      <h2>CRUD Objetos</h2>
      <div style={{ textAlign: "center", marginBottom: "12px" }}>
        <input
          value={nombre}
          onChange={e => setNombre(e.target.value)}
          placeholder="Nombre del objeto"
        />
        {editId ? (
          <>
            <button onClick={handleUpdate}>Actualizar</button>
            <button onClick={handleCancel} style={{ background: "#bbb", color: "#222" }}>Cancelar</button>
          </>
        ) : (
          <button onClick={handleAdd}>Agregar</button>
        )}
      </div>
      {mensaje && <p style={{ color: "green", textAlign: "center" }}>{mensaje}</p>}
      {error && <p style={{ color: "red", textAlign: "center" }}>{error}</p>}
      <table className="crud-table">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          {objetos.map(obj => (
            <tr key={obj.id}>
              <td>{obj.nombre}</td>
              <td>
                <button onClick={() => handleEdit(obj)}>Editar</button>
                <button onClick={() => handleDelete(obj.id)} style={{ background: "#c62828" }}>Borrar</button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
