// vue-app/src/components/Login.vue
<script setup>
import { ref } from "vue";
import { db } from "../firebaseConfig";
import { collection, query, where, getDocs, addDoc } from "firebase/firestore";

const emit = defineEmits(["login"]);
const nombre = ref("");
const password = ref("");
const error = ref("");
const success = ref("");

const handleLogin = async () => {
  error.value = "";
  success.value = "";
  if (!nombre.value || !password.value) {
    error.value = "Completa todos los campos.";
    return;
  }
  const q = query(
    collection(db, "usuarios"),
    where("nombre", "==", nombre.value),
    where("password", "==", password.value)
  );
  const querySnapshot = await getDocs(q);
  if (!querySnapshot.empty) {
    success.value = "¡Bienvenido!";
    setTimeout(() => emit("login"), 800);
  } else {
    error.value = "Usuario o contraseña incorrectos. ¿Deseas registrarte?";
  }
};

const handleRegister = async () => {
  error.value = "";
  success.value = "";
  if (!nombre.value || !password.value) {
    error.value = "Completa todos los campos.";
    return;
  }
  const q = query(
    collection(db, "usuarios"),
    where("nombre", "==", nombre.value)
  );
  const querySnapshot = await getDocs(q);
  if (!querySnapshot.empty) {
    error.value = "El usuario ya existe.";
    return;
  }
  await addDoc(collection(db, "usuarios"), {
    nombre: nombre.value,
    password: password.value,
  });
  success.value = "Usuario registrado. Ahora puedes ingresar.";
};
</script>

<template>
  <form class="crud-container" @submit.prevent="handleLogin">
    <h2>Login</h2>
    <input v-model="nombre" placeholder="Nombre" autofocus /><br />
    <input v-model="password" type="password" placeholder="Contraseña" /><br />
    <button type="submit" style="margin-right:8px">Ingresar</button>
    <button type="button" @click="handleRegister">Registrar</button>
    <p v-if="error" style="color:red">{{ error }}</p>
    <p v-if="success" style="color:green">{{ success }}</p>
  </form>
</template>

<style scoped>
.read-the-docs {
  color: #888;
}
</style>

// react-app/src/Componentes/Login.js
import React, { useState } from "react";
import { db } from "../firebaseConfig";
import { collection, query, where, getDocs, addDoc } from "firebase/firestore";

export default function Login({ onLogin }) {
  const [nombre, setNombre] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");

  const handleLogin = async (e) => {
    e.preventDefault();
    setError("");
    setSuccess("");
    if (!nombre || !password) {
      setError("Completa todos los campos.");
      return;
    }
    try {
      const q = query(
        collection(db, "usuarios"),
        where("nombre", "==", nombre),
        where("password", "==", password)
      );
      const querySnapshot = await getDocs(q);
      if (!querySnapshot.empty) {
        setSuccess("¡Bienvenido!");
        setTimeout(() => onLogin(), 800);
      } else {
        setError("Usuario o contraseña incorrectos. ¿Deseas registrarte?");
      }
    } catch (err) {
      setError("Error al conectar con la base de datos.");
    }
  };

  const handleRegister = async (e) => {
    e.preventDefault();
    setError("");
    setSuccess("");
    if (!nombre || !password) {
      setError("Completa todos los campos.");
      return;
    }
    try {
      // Verifica si ya existe el usuario
      const q = query(
        collection(db, "usuarios"),
        where("nombre", "==", nombre)
      );
      const querySnapshot = await getDocs(q);
      if (!querySnapshot.empty) {
        setError("El usuario ya existe.");
        return;
      }
      await addDoc(collection(db, "usuarios"), { nombre, password });
      setSuccess("Usuario registrado. Ahora puedes ingresar.");
    } catch (err) {
      setError("Error al registrar usuario.");
    }
  };

  return (
    <form className="crud-container" style={{ maxWidth: 350 }}>
      <h2>Login</h2>
      <input
        type="text"
        placeholder="Nombre"
        value={nombre}
        onChange={e => setNombre(e.target.value)}
        autoFocus
      /><br />
      <input
        type="password"
        placeholder="Contraseña"
        value={password}
        onChange={e => setPassword(e.target.value)}
      /><br />
      <button onClick={handleLogin} style={{ marginRight: 8 }}>Ingresar</button>
      <button onClick={handleRegister} type="button">Registrar</button>
      {error && <p style={{ color: "red" }}>{error}</p>}
      {success && <p style={{ color: "green" }}>{success}</p>}
    </form>
  );
}
